#ifndef STRUCTS_H
#define STRUCTS_H

#include <QtGui>

//ALWAYS HAVE NUMBER OF RULES AS LAST ELEMENT, WORKS AS ruleType.size()
//FOLDERNAME_CONTAINS
/*enum ruleType{ FILENAME_CONTAINS, TAG_TITLE_CONTAINS, TAG_ARTIST_CONTAINS,\
	TAG_ALBUM_CONTAINS, TAG_YEAR_IS, TAG_COMMENT_CONTAINS, TAG_TRACK_IS, TAG_GENRE_CONTAINS, AUDIO_BITRATE_IS, AUDIO_SAMPLERATE_IS,\
	AUDIO_CHANNELS_IS, AUDIO_LENGTH_IS, NUMBEROFRULES };
	*/

enum fileReadResult{ DOESNOTEXIST, EXISTS, NOTVALID };

const QString ext = ".ini"; //extension of QSettings files
const QString defaultExt = "*.mp3;*.wma;*.wav;*.ogg;*.aac;*.ac3;*.m4a";

#endif
